[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = "2021"
name = "spk-solve-package-iterator"
version = "0.36.0"

[dependencies]
async-trait = "0.1"
dyn-clone = "1.0"
futures = "0.3.9"
once_cell = "1.8"
spk-solve-solution = { path = "../solution" }
spk-schema = { path = "../../../spk-schema" }
spk-storage = { path = "../../../spk-storage" }
thiserror = "1.0"
tokio = { version = "1.20", features = ["rt"] }
tracing = "0.1.35"

[dev-dependencies]
itertools = "0.10"
rstest = "0.15.0"
spk-solve = { path = "../.." }
