[package]
authors = { workspace = true }
edition = { workspace = true }
name = "spk-cmd-make-recipe"
version = { workspace = true }

[lints]
workspace = true

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
miette = { workspace = true, features = ["fancy"] }
clap = { workspace = true, features = ["derive", "env"] }
spk-cli-common = { workspace = true }
spk-schema = { workspace = true }
spk-schema-liquid = { workspace = true }
tracing = "0.1.35"
