[package]
authors = { workspace = true }
edition = { workspace = true }
name = "spfs-cli-render"
version = { workspace = true }

[lints]
workspace = true

[[bin]]
name = "spfs-render"
path = "src/cmd_render.rs"

[features]
sentry = ["spfs-cli-common/sentry"]

[dependencies]
clap = { workspace = true }
dunce = { workspace = true }
futures = { workspace = true }
miette = { workspace = true, features = ["fancy"] }
serde_json = { workspace = true }
spfs = { workspace = true }
spfs-cli-common = { workspace = true }
strum = { workspace = true, features = ["derive"] }
tokio = { version = "1.20", features = ["rt", "rt-multi-thread"] }
tracing = { workspace = true }
