
stages:
  - test
  - build
  - deploy

test:
  tags: [docker]
  stage: test
  only:
    - merge_requests
    - master
    - tags
  script:
    - unset PYTHONNOUSERSITE
    - pip3 install --force-reinstall --user pipenv
    - pipenv --three sync --dev
    - pipenv run pytest

build:
  tags: [docker]
  stage: build
  only:
    - tags
    - merge_requests
  script:
    - ./build_rpm.sh
  artifacts:
    paths:
      - build/*/*.rpm
    expire_in: 1 week

deploy:
  tags: [rhel7]
  stage: deploy
  only:
    - tags
  script:
    - tree build/rpm/*
    - rsync -rvm --include="*/" --include="*.rpm" --exclude="*" build/* /net/yum/spi-dev/
    - createrepo /net/yum/spi-dev
  artifacts:
    paths:
      - build/*/*.rpm
    expire_in: 10 yrs
