
stages:
  - test
  - build
  - deploy

test:
  tags: [docker]
  stage: test
  only:
    - merge_requests
    - master
    - tags
  script:
    - unset PYTHONNOUSERSITE
    - python37 -m pip install --user pipenv
    - ~/.local/bin/pipenv --three sync --dev
    - ~/.local/bin/pipenv run pytest

build:
  tags: [docker]
  stage: build
  only:
    - tags
    - merge_requests
  script:
    - ./build_rpm.sh
  artifacts:
    paths:
      - build/*/*.rpm
    expire_in: 1 week

deploy:
  tags: [rhel7]
  stage: deploy
  only:
    - tags
  variables:
    SENTRY_RELEASE_HOOK: http://sentry.spimageworks.com/api/hooks/release/builtin/5/43c925ac42211367d4fd9e6d0e80065482477c412d12963e1829c7b673ab2f06/
  script:
    - tree build/rpm/*
    - rsync -rvm --include="*/" --include="*.rpm" --exclude="*" build/* /net/yum/spi-dev/
    - createrepo /net/yum/spi-dev
    - version=$(echo "$CI_COMMIT_REF_NAME" | sed 's|v||')
    - >
      curl $SENTRY_RELEASE_HOOK -X POST -H 'Content-Type: application/json' -d
      '{"version": "'$version'", "refs": [{"repository": "dev-group/dev-ops/spenv", "commit": "'$CI_COMMIT_SHA'" }]}'
  artifacts:
    paths:
      - build/*/*.rpm
    expire_in: 10 yrs
