
build:
  tags: [rehl7]
  script:
    - build_rpm.sh
  artifacts:
    paths:
      - build/rpm/*/*.rpm
    expire_in: 1 week

deploy:
  when:
    - manual
  script:
    - tree build/rpm/*
    - rsync -rvm --include="*/" --include="*.rpm" --exclude="*" build/rpm/* /net/yum/spi-dev/
    - createrepo /net/yum/spi-dev
  artifacts:
    paths:
      build/rpm/*/*.rpm
    expire_in: 10 yrs
