
stages:
  - build
  - deploy

build:
  tags: [docker]
  only:
    - master
    - merge_requests
  script:
    - ./build_rpm.sh
  artifacts:
    paths:
      - build/rpm/*/*.rpm
    expire_in: 1 week

deploy:
  tags: [rhel7]
  only:
    - master
  script:
    - tree build/rpm/*
    - rsync -rvm --include="*/" --include="*.rpm" --exclude="*" build/rpm/* /net/yum/spi-dev/
    - createrepo /net/yum/spi-dev
  artifacts:
    paths:
      - build/rpm/*/*.rpm
    expire_in: 10 yrs
