version: 0.15.0
release_notes: |
  * No longer commits empty layers on top of platforms
  * Will no longer commit an empty layer from the command line

environment:
  kind: PipEnv

components:
  - name: lib
    kind: PythonPackage
    linting:
      python3_compatibility: False
  - name: rpm
    kind: RPMPackage
    spec_file: spfs.spec
