version: 0.19.1
release_notes: |
  * Fix bug where masked files were not properly removed
  * Improve startup performance by moving file masking into spfs-enter

environment:
  kind: PipEnv

components:
- name: python
  kind: PythonPackage
  lint:
    python3: false
    black: true
    mypy: true
  test:
    command: pytest
  install:
    enabled: true

- name: rpm
  kind: RPMPackage
  spec_file: spfs.spec

- kind: HugoDocs
  name: docs
  location: docs
