version: 0.27.0
release_notes: |
  * Update render process to survive repository files being owned by other users
    * Separate core rendering process into separate binary with cap_chown
    * Take ownership of local repo files forcefully if needed to complete a render

toolchain:
  - kind: Rust

components:
  - kind: RustBinary
    name: spfs

  - name: rpm
    kind: RPMPackage
    spec_file: spfs.spec

  - kind: HugoDocs
    name: docs
    location: docs

  - kind: SentryRelease
    name: sentry
    project: spfs
    deploy.enabled: true
