version: 0.21.1
release_notes: |
  * Fix bug where sync process could leave out some files
  * Fix bug where renders could fail uselessly because a directory already exists

toolchain:
  - kind: Rust

components:
  - kind: RustBinary
    name: spfs

  - name: rpm
    kind: RPMPackage
    spec_file: spfs.spec

  - kind: HugoDocs
    name: docs
    location: docs

  - kind: SentryRelease
    name: sentry
    project: spfs
    deploy.enabled: true
