version: 0.20.12
release_notes: |
  * Update clean command to be faster on large repos
    * Don't print all ids before cleaning
    * Fix bug where it tried to clean the same thing many times

toolchain:
  - kind: Pipenv

components:
  - name: python
    kind: PythonPackage
    lint:
      python3: false
      black: true
      mypy: true
    test:
      command: pytest
    install:
      enabled: true
    deploy:
      rez:
        enabled: false

  - name: rpm
    kind: RPMPackage
    spec_file: spfs.spec

  - kind: HugoDocs
    name: docs
    location: docs

  - kind: SentryRelease
    name: sentry
    project: spfs
    deploy.enabled: true
