version: 0.19.7
release_notes: |
  * Fix bug where diff command could error for new files
  * Fix bug where full digest could not be used in sync api

environment:
  kind: PipEnv

components:
- name: python
  kind: PythonPackage
  lint:
    python3: false
    black: true
    mypy: true
  test:
    command: pytest
  install:
    enabled: true
  deploy:
    rez:
      enabled: false

- name: rpm
  kind: RPMPackage
  spec_file: spfs.spec

- kind: HugoDocs
  name: docs
  location: docs
