version: 0.15.1
release_notes: |
  * Add diff command for comparing refs on the command line
  * Improve manifest performance for overall gains

environment:
  kind: PipEnv

components:
  - name: lib
    kind: PythonPackage
    lint:
      python3: false
      black: true
    test:
      command: pytest
    install:
      enabled: true
  - name: rpm
    kind: RPMPackage
    spec_file: spfs.spec
