version: 0.24.0
release_notes: |
  * Add new subcommand that can render files into any local directory
    * This is basically a usable export of the spfs file system to be
      archived or used where spfs may not be otherwise available

toolchain:
  - kind: Rust

components:
  - kind: RustBinary
    name: spfs

  - name: rpm
    kind: RPMPackage
    spec_file: spfs.spec

  - kind: HugoDocs
    name: docs
    location: docs

  - kind: SentryRelease
    name: sentry
    project: spfs
    deploy.enabled: true
