version: 0.20.9
release_notes: |
  * Improve sync speed for huge filesets (tens of thousands)

toolchain:
  - kind: Pipenv

components:
  - name: python
    kind: PythonPackage
    lint:
      python3: false
      black: true
      mypy: true
    test:
      command: pytest
    install:
      enabled: true
    deploy:
      rez:
        enabled: false

  - name: rpm
    kind: RPMPackage
    spec_file: spfs.spec

  - kind: HugoDocs
    name: docs
    location: docs

  - kind: SentryRelease
    name: sentry
    project: spfs
    deploy.enabled: true
