version: 0.19.0
release_notes: |
  * Imrove performance when entering environments with many files

environment:
  kind: PipEnv

components:
- name: python
  kind: PythonPackage
  lint:
    python3: false
    black: true
    mypy: true
  test:
    command: pytest
  install:
    enabled: true

- name: rpm
  kind: RPMPackage
  spec_file: spfs.spec

- kind: HugoDocs
  name: docs
  location: docs
