version: 0.19.5
release_notes: |
  * Fix bug where has_tag returned true when tag was empty
  * Update semver and add has_tag to repos
  * Add functionality to list under tag paths like ls
  * Remove missed debug print statements
  * Move cli diff code into top-level api function for easier access

environment:
  kind: PipEnv

components:
- name: python
  kind: PythonPackage
  lint:
    python3: false
    black: true
    mypy: true
  test:
    command: pytest
  install:
    enabled: true
  deploy:
    rez:
      enabled: false

- name: rpm
  kind: RPMPackage
  spec_file: spfs.spec

- kind: HugoDocs
  name: docs
  location: docs
