version: 0.21.0
release_notes: |
  * Convert existing spfs python code to rust

toolchain:
  - kind: Pipenv

  - kind: Rust
components:
  - name: python
    kind: PythonPackage
    lint:
      python3: false
      black: true
      mypy: true
    test:
      command: pytest
    install:
      enabled: true
    deploy:
      rez:
        enabled: false

  - kind: RustBinary
    name: rust

  - name: rpm
    kind: RPMPackage
    spec_file: spfs.spec

  - kind: HugoDocs
    name: docs
    location: docs

  - kind: SentryRelease
    name: sentry
    project: spfs
    deploy.enabled: true
