version: 0.18.0
release_notes: |
  * Update clean command to prompt before deletion
  * Add ls and cat-file commands for introspection
  * Update info command not to print diffs - returning much faster
  * Update diff command show current runtime <=> current changes by default
  * Add more advanced info to documentation
  * Update tag log to show target, not tag digest
  * Multiple bug fixes from latest refactoring

environment:
  kind: PipEnv

components:
- name: python
  kind: PythonPackage
  lint:
    python3: false
    black: true
    mypy: true
  test:
    command: pytest
  install:
    enabled: true

- name: rpm
  kind: RPMPackage
  spec_file: spfs.spec

- kind: HugoDocs
  name: docs
  location: docs
