version: 0.16.1
release_notes: |
  * Allow listing of remote data from command line
  * Provide basic pruning behaviour for old tag data
  * Resolve issue where digest shortening was dangerous
    * Update to calucluate shortes unambigous properly, not assume

environment:
  kind: PipEnv

components:
- name: python
  kind: PythonPackage
  lint:
    python3: false
    black: true
    mypy: true
  test:
    command: pytest
  install:
    enabled: true

- name: rpm
  kind: RPMPackage
  spec_file: spfs.spec

- kind: HugoDocs
  name: docs
  location: docs
