version: 0.20.8
release_notes: |
  * Fix bug where creating a new runtime failed from non-editable runtimes, even
    though the error was non-fatal and should have continued

toolchain:
  - kind: Pipenv

components:
  - name: python
    kind: PythonPackage
    lint:
      python3: false
      black: true
      mypy: true
    test:
      command: pytest
    install:
      enabled: true
    deploy:
      rez:
        enabled: false

  - name: rpm
    kind: RPMPackage
    spec_file: spfs.spec

  - kind: HugoDocs
    name: docs
    location: docs

  - kind: SentryRelease
    name: sentry
    project: spfs
    deploy.enabled: true
