version: 0.20.2
release_notes: |
  * Fix bug where reset/remount would fail with 'device or resource busy'
  * Fix bux where only - could be given as ref during reset

toolchain:
  - kind: Pipenv

components:
- name: python
  kind: PythonPackage
  lint:
    python3: false
    black: true
    mypy: true
  test:
    command: pytest
  install:
    enabled: true
  deploy:
    rez:
      enabled: false

- name: rpm
  kind: RPMPackage
  spec_file: spfs.spec

- kind: HugoDocs
  name: docs
  location: docs

- kind: SentryRelease
  name: sentry
  project: spfs
  deploy.enabled: true
