version: 0.26.0
release_notes: |
  * Convert spfs-enter command to rust
  * Externalize the run and shell commands
  * Update init command to work for pre-baked environments

toolchain:
  - kind: Rust

components:
  - kind: RustBinary
    name: spfs

  - name: rpm
    kind: RPMPackage
    spec_file: spfs.spec

  - kind: HugoDocs
    name: docs
    location: docs

  - kind: SentryRelease
    name: sentry
    project: spfs
    deploy.enabled: true
