version: 0.22.2
release_notes: |
  * Add logic to flatten layers when over a configured maximum
    * This happens seamlessly on-the-fly and allows circumventing
      limits in overlayfs and the operating system
  * Improve tar repository api for easier flushing of data to archive

toolchain:
  - kind: Rust

components:
  - kind: RustBinary
    name: spfs

  - name: rpm
    kind: RPMPackage
    spec_file: spfs.spec

  - kind: HugoDocs
    name: docs
    location: docs

  - kind: SentryRelease
    name: sentry
    project: spfs
    deploy.enabled: true
