version: 0.17.0
release_notes: |
  * Allow spfs runtimes to be mounted in read-only mode
  * Add command line subcommand and flag to enable editing
    * Use read-only mount by default for exiting environments
  * Update the spfs-enter command with actual option parsing
  * Update the spfs-enter command to allow remounting
  * Remount as read-only whenever a layer is created in the edit mode

environment:
  kind: PipEnv

components:
- name: python
  kind: PythonPackage
  lint:
    python3: false
    black: true
    mypy: true
  test:
    command: pytest
  install:
    enabled: true

- name: rpm
  kind: RPMPackage
  spec_file: spfs.spec

- kind: HugoDocs
  name: docs
  location: docs
