version: 0.14.1

environment:
  kind: PipEnv

components:
  - name: lib
    kind: PythonPackage
    linting:
      python3_compatibility: False
  - name: rpm
    kind: RPMPackage
    spec_file: spfs.spec
