version: 0.19.9
release_notes: |
  * Remove confusing output for tar repo
  * Fix bug in reading tags from tar archive
  * Remove spfs import from setup.py
  * Allow blobs to by synced directly by digest/tag

toolchain:
  - kind: Pipenv

components:
- name: python
  kind: PythonPackage
  lint:
    python3: false
    black: true
    mypy: true
  test:
    command: pytest
  install:
    enabled: true
  deploy:
    rez:
      enabled: false

- name: rpm
  kind: RPMPackage
  spec_file: spfs.spec

- kind: HugoDocs
  name: docs
  location: docs
