version: 0.23.0
release_notes: |
  * Update local renders to be divided by username
    * This will duplicate renders and use additional inodes, but resolves
      many permissions issues that could be encountered when users share machines
  * Update local renders to use a working directory while rendering
    * This helps to aleviate collisions of mutliple processes rendering a layer
      at the same time, just like is done when writing all other object types.

toolchain:
  - kind: Rust

components:
  - kind: RustBinary
    name: spfs

  - name: rpm
    kind: RPMPackage
    spec_file: spfs.spec

  - kind: HugoDocs
    name: docs
    location: docs

  - kind: SentryRelease
    name: sentry
    project: spfs
    deploy.enabled: true
