version: 0.15.2
release_notes: |
  * Add getting started documentation
  * Update pipeline for changes to spdev component specs

environment:
  kind: PipEnv

components:
- name: lib
  kind: PythonPackage
  lint:
    python3: false
    black: true
  test:
    command: pytest
  install:
    enabled: true

- name: rpm
  kind: RPMPackage
  spec_file: spfs.spec

- kind: HugoDocs
  name: docs
  location: docs
