version: 0.16.0
release_notes: |
  * Ensure tag data is unaltered during sync process
  * Add clean command to remove orphaned object from storage
  * Refactor storage api to streamline operations over the entire repository (eg clean)
  * Move to binary storage format for objects to reduce size and improve io
  * Add migration command and logic for this upgrade in formats

environment:
  kind: PipEnv

components:
- name: python
  kind: PythonPackage
  lint:
    python3: false
    black: true
    mypy: true
  test:
    command: pytest
  install:
    enabled: true

- name: rpm
  kind: RPMPackage
  spec_file: spfs.spec

- kind: HugoDocs
  name: docs
  location: docs
