[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
default-run = "spfs"
edition = "2021"
name = "spfs"
version = "0.34.3"

[lib]
name = "spfs"
path = "src/lib.rs"

[[bin]]
name = "spfs"
path = "src/cli/bin.rs"
[[bin]]
name = "spfs-run"
# use a separate module so cmd_run can also be importable from cmd_shell
path = "src/cli/cmd_run_main.rs"
[[bin]]
name = "spfs-shell"
path = "src/cli/cmd_shell.rs"
[[bin]]
name = "spfs-enter"
path = "src/cli/cmd_enter.rs"
[[bin]]
name = "spfs-join"
path = "src/cli/cmd_join.rs"
[[bin]]
name = "spfs-pull"
path = "src/cli/cmd_pull.rs"
[[bin]]
name = "spfs-push"
path = "src/cli/cmd_push.rs"
[[bin]]
name = "spfs-render"
path = "src/cli/cmd_render.rs"
[[bin]]
name = "spfs-monitor"
path = "src/cli/cmd_monitor.rs"
[[bin]]
name = "spfs-server"
path = "src/cli/cmd_server.rs"
required-features = ["server"]

[features]
default = ["server"]

# If enabled, will create the "local" repository in a subdirectory
# of the standard storage root, named "ci/pipeline_${CI_PIPELINE_ID}".
gitlab-ci-local-repo-isolation = []
sentry = ["dep:sentry"]
server = [
    "tokio/signal",
    "tokio-stream/net",
    "hyper/server",
    "tokio-util/codec",
    "tokio-util/io",
    "tokio-util/io-util",
]
"runtime-compat-0.33" = []

[dependencies]
async-trait = "0.1.52"
async-recursion = "1.0"
async-stream = "0.3"
caps = "0.5.3"
chrono = { version = "0.4.19", features = ["serde"] }
clap = { version = "3.1.6", features = ["derive", "env"] }
close-err = "1.0"
cnproc = { git = "https://github.com/rydrman/cnproc-rs", branch = "act-like-iterator" }
colored = "2.0.0"
config = "0.12.0"
data-encoding = "2.3.0"
expanduser = "1.2.1"
faccess = "0.2.3"
futures = "0.3.9"
gitignore = "1.0.7"
glob = "0.3.0"
hyper = { version = "0.14.16", features = ["client"] }
indicatif = "0.16.2"
itertools = "0.9.0"
lazy_static = "1.4.0"
libc = "0.2.80"
nix = "0.19.0"
once_cell = "1.8.0"
palaver = "0.2.8"
prost = "0.9.0"
rand = "0.7.3"
relative-path = "1.3.2"
reqwest = { version = "0.11.7", features = ["stream"] }
ring = "0.16.15"
semver = "0.11.0"
sentry = { version = "0.21.0", optional = true }
serde = { version = "1.0.117", features = ["derive"] }
serde_derive = "1.0.118"
serde_json = "1.0.57"
serde_qs = "0.9.1"
strum = "0.21"
strum_macros = "0.21"
tar = "0.4.30"
tempdir = "0.3.7"
tempfile = "3.3"
tokio = { version = "1.15", features = [
    "fs",
    "io-util",
    "io-std",
    "rt",
    "rt-multi-thread",
    "macros",
    "sync",
    "process",
] }
tokio-stream = { version = "0.1", features = ["net"], optional = true }
tokio-util = { version = "0.6", features = ["compat"] }
tonic = "0.6.1"
tracing = "0.1.22"
tracing-subscriber = "0.2.15"
url = { version = "2.2.0", features = ["serde"] }
uuid = { version = "0.8.1", features = ["v4"] }
walkdir = "2.3.1"
whoami = "0.9.0"
thiserror = "1.0"

[build-dependencies]
tonic-build = "0.6.0"

[dev-dependencies]
criterion = { version = "0.3", features = ["async_tokio", "html_reports"] }
rstest = { version = "0.12", default_features = false }
serial_test = "0.5.1"

[[bench]]
name = "spfs_bench"
harness = false
