[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = "2018"
name = "spfs"
version="0.20.12"

[lib]
name = "spfs"
path = "src/lib.rs"

# [[bin]]
# name = "spfs"
# path = "src/cli/bin.rs"

[dependencies]
data-encoding = "2.3.0"
nix = "0.19.0"
ring = "0.16.15"
unicode_reader = "1.0.1"

[dev-dependencies]
rstest = "0.6.4"
rand = "0.7.3"
