[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = "2018"
name = "spfs"
version = "0.20.12"

[lib]
name = "spfs"
path = "src/lib.rs"

[[bin]]
name = "spfs"
path = "src/cli/bin.rs"

[dependencies]
chrono = "0.4.19"
data-encoding = "2.3.0"
gitignore = "1.0.7"
glob = "0.3.0"
itertools = "0.9.0"
libc = "0.2.80"
nix = "0.19.0"
relative-path = "1.3.2"
ring = "0.16.15"
rstest = "0.6.4"
sentry = "0.21.0"
serde = {version = "1.0.117", features = ["derive"]}
serde_json = "1.0.57"
tracing = "0.1.22"
unicode_reader = "1.0.1"
url = "2.2.0"
uuid = {version = "0.8.1", features = ["v4"]}
walkdir = "2.3.1"
whoami = "0.9.0"
structopt = "0.3.21"

[dev-dependencies]
rand = "0.7.3"
rstest = "0.6.4"
tempdir = "0.3.7"
