[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
default-run = "spfs"
edition = "2018"
name = "spfs"
version = "0.29.0"

[lib]
name = "spfs"
path = "src/lib.rs"

[[bin]]
name = "spfs"
path = "src/cli/bin.rs"
[[bin]]
name = "spfs-run"
# use a separate module so cmd_run can also be importable from cmd_shell
path = "src/cli/cmd_run_main.rs"
[[bin]]
name = "spfs-shell"
path = "src/cli/cmd_shell.rs"
[[bin]]
name = "spfs-enter"
path = "src/cli/cmd_enter.rs"
[[bin]]
name = "spfs-join"
path = "src/cli/cmd_join.rs"
[[bin]]
name = "spfs-pull"
path = "src/cli/cmd_pull.rs"
[[bin]]
name = "spfs-push"
path = "src/cli/cmd_push.rs"
[[bin]]
name = "spfs-init"
path = "src/cli/cmd_init.rs"
[[bin]]
name = "spfs-render"
path = "src/cli/cmd_render.rs"

[dependencies]
caps = "0.5.3"
chrono = "0.4.19"
colored = "2.0.0"
config = "0.10.1"
data-encoding = "2.3.0"
expanduser = "1.2.1"
faccess = "0.2.3"
futures = "0.3.9"
gitignore = "1.0.7"
glob = "0.3.0"
indicatif = {version = "0.15.0", features = ["rayon"]}
itertools = "0.9.0"
libc = "0.2.80"
nix = "0.19.0"
palaver = "0.2.8"
rand = "0.7.3"
rayon = "1.5.0"
relative-path = "1.3.2"
ring = "0.16.15"
rstest = "0.6.4"
semver = "0.11.0"
sentry = "0.21.0"
serde = {version = "1.0.117", features = ["derive"]}
serde_derive = "1.0.118"
serde_json = "1.0.57"
structopt = "0.3.21"
strum = "0.21"
strum_macros = "0.21"
tar = "0.4.30"
tempdir = "0.3.7"
tracing = "0.1.22"
tracing-subscriber = "0.2.15"
unicode_reader = "1.0.1"
url = "2.2.0"
uuid = {version = "0.8.1", features = ["v4"]}
walkdir = "2.3.1"
whoami = "0.9.0"
thiserror = "1.0"

[dev-dependencies]
rstest = "0.6.4"
serial_test = "0.5.1"
