[package]
authors = { workspace = true }
edition = { workspace = true }
name = "spfs-encoding"
version = { workspace = true }

[lints]
workspace = true

[dependencies]
data-encoding = "2.3"
ring = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tokio = { version = "1.20", features = ["io-util", "io-std"] }
thiserror = { workspace = true }
miette = { workspace = true }

[dev-dependencies]
rstest = { version = "0.15.0", default_features = false }
rand = "0.8.5"
