version: 0.2.0
release_notes: |
  * Final MVP Feature Release
    * Add repository selection and publishing to command line and API
    * Add simple commands to list packages/versions/builds in a repo
    * Improve solver and command line error output
    * Improve documentation around working with the solver
    * Allow specifying build options on the command line


environment:
  kind: PipEnv
  variables:
    SENTRY_ENVIRONMENT: development

components:

- kind: PythonPackage
  name: python
  lint:
    black: true
    python3: false
    mypy: true
  test:
    command: spfs run - pytest
  install:
    enabled: true
  deploy:
    rez.enabled: false

- kind: HugoDocs
  name: docs
  location: docs
- kind: RPMPackage
  name: rpm
  spec_file: spk.spec
