version: 0.6.0
release_notes: |
  * Update compatibility so that binary compat will also fail on api incompat
  * Update compatibility checks to return error strings for easier tracking and debugging
  * Add additional solver output layer that explains each skipped version
  * Update storage to store complete spec with each build, to enable pinning
  * Allow pinning of packages from the build environment, to ease variant creation

toolchain:
- kind: Shell
  variables:
    SENTRY_ENVIRONMENT: development
- kind: Pipenv

components:

- kind: PythonPackage
  name: python
  lint:
    black: true
    python3: false
    mypy: true
  test:
    command: spfs run - pytest
  install:
    enabled: true
  deploy:
    rez.enabled: false

- kind: HugoDocs
  name: docs
  location: docs
- kind: RPMPackage
  name: rpm
  spec_file: spk.spec
