version: 0.2.2
release_notes: |
  * Allow repos to be specified for make-binary command
  * Update cmake example with variant
  * Add recipe for gcc 63 stub package
  * Update docs with information on spec build section

environment:
  kind: PipEnv
  variables:
    SENTRY_ENVIRONMENT: development

components:

- kind: PythonPackage
  name: python
  lint:
    black: true
    python3: false
    mypy: true
  test:
    command: spfs run - pytest
  install:
    enabled: true
  deploy:
    rez.enabled: false

- kind: HugoDocs
  name: docs
  location: docs
- kind: RPMPackage
  name: rpm
  spec_file: spk.spec
