version: 0.21.0
release_notes: |
  # Solver 2.0

  This update rebuilds the solver to solve bugs that could not
  be fixed due to limitation in the previous architecture. This
  new iteration also cleans up the codebase, capturing validation
  and decision logic in bite-sized, purpose built classes. This
  makes the solver code much easier to read, maintain, extend, and test.

toolchain:
  - kind: Shell
    variables:
      SENTRY_ENVIRONMENT: development
      PATH: $SPDEV_ENV/bin:$PATH
  - kind: Pipenv

components:
  - kind: PythonPackage
    name: python
    lint:
      black: true
      python3: false
      mypy: true
    test:
      command: spfs run - pytest
    install:
      enabled: true
    deploy:
      rez.enabled: false

  - kind: HugoDocs
    name: docs
    location: docs

  - kind: RPMPackage
    name: rpm
    spec_file: spk.spec

    # bootstrap packages that need to go out with any new features
  - kind: SPKPackage
    name: spk-stdfs
    version: 1.0.0
    spec_file: packages/stdfs/stdfs.spk.yaml
  - kind: SPKPackage
    name: spk-gcc48
    version: 4.8.5
    spec_file: packages/gcc/gcc48.spk.yaml
  - kind: SPKPackage
    name: spk-gcc63
    version: 6.3.1
    spec_file: packages/gcc/gcc63.spk.yaml

  - kind: SentryRelease
    name: sentry
    project: spk
    deploy:
      enabled: true

  - kind: WordpressReleaseNotes
    name: wp-release
    email:
      sender:
        name: SPK Team
