version: 0.7.0
release_notes: |
  * Add the ability to specify optional dependencies
    * Optional dependencies are only taken into account if the package is already installed or requested by another package
    * This is done via the 'include' field of the package request (which can be 'Always' or 'IfAlreadyPresent')

toolchain:
- kind: Shell
  variables:
    SENTRY_ENVIRONMENT: development
- kind: Pipenv

components:

- kind: PythonPackage
  name: python
  lint:
    black: true
    python3: false
    mypy: true
  test:
    command: spfs run - pytest
  install:
    enabled: true
  deploy:
    rez.enabled: false

- kind: HugoDocs
  name: docs
  location: docs
- kind: RPMPackage
  name: rpm
  spec_file: spk.spec
