version: 0.4.1
release_notes: |
  * Update install command to separate requested from dependecies
  * Fix publish command so it processes all args

environment:
  kind: PipEnv
  variables:
    SENTRY_ENVIRONMENT: development

components:

- kind: PythonPackage
  name: python
  lint:
    black: true
    python3: false
    mypy: true
  test:
    command: spfs run - pytest
  install:
    enabled: true
  deploy:
    rez.enabled: false

- kind: HugoDocs
  name: docs
  location: docs
- kind: RPMPackage
  name: rpm
  spec_file: spk.spec
