version: 0.5.0
release_notes: |
  * Add support for pre and post release tags on version numbers
  * Ensure proposed naming convention is enforced
  * Add file to build process to store build options
  * Update ls command to be able to print build options for each package build

toolchain:
- kind: Shell
  variables:
    SENTRY_ENVIRONMENT: development
- kind: Pipenv

components:

- kind: PythonPackage
  name: python
  lint:
    black: true
    python3: false
    mypy: true
  test:
    command: spfs run - pytest
  install:
    enabled: true
  deploy:
    rez.enabled: false

- kind: HugoDocs
  name: docs
  location: docs
- kind: RPMPackage
  name: rpm
  spec_file: spk.spec
