version: 0.7.3
release_notes: |
  * Update ls command to be more callable programatically

toolchain:
- kind: Shell
  variables:
    SENTRY_ENVIRONMENT: development
- kind: Pipenv

components:

- kind: PythonPackage
  name: python
  lint:
    black: true
    python3: false
    mypy: true
  test:
    command: spfs run - pytest
  install:
    enabled: true
  deploy:
    rez.enabled: false

- kind: HugoDocs
  name: docs
  location: docs
- kind: RPMPackage
  name: rpm
  spec_file: spk.spec
