version: 0.9.0
release_notes: |
  * Include published spec in package binary build
    * So that installed packages can be viewed via /spfs
  * Update install command to account for existing packages
  * Add support for local environment files
    * To enable the creation and tracking of development environments
      not unlike tools such as pipenv and npm


toolchain:
- kind: Shell
  variables:
    SENTRY_ENVIRONMENT: development
- kind: Pipenv

components:

- kind: PythonPackage
  name: python
  lint:
    black: true
    python3: false
    mypy: true
  test:
    command: spfs run - pytest
  install:
    enabled: true
  deploy:
    rez.enabled: false

- kind: HugoDocs
  name: docs
  location: docs
- kind: RPMPackage
  name: rpm
  spec_file: spk.spec
