version: 0.8.0
release_notes: |
  * Build from source packages by default
    * The build command will produce a source package and binary package
    * CWD during binary build will the the source package under /spfs
    * Any artifacts left under CWD are cleaned and not packaged

toolchain:
- kind: Shell
  variables:
    SENTRY_ENVIRONMENT: development
- kind: Pipenv

components:

- kind: PythonPackage
  name: python
  lint:
    black: true
    python3: false
    mypy: true
  test:
    command: spfs run - pytest
  install:
    enabled: true
  deploy:
    rez.enabled: false

- kind: HugoDocs
  name: docs
  location: docs
- kind: RPMPackage
  name: rpm
  spec_file: spk.spec
