version: 0.1.0
release_notes: |
  * Initial MVP release
   * Build package from spec file
   * Define package with dependencies and string options
   * Store packages as spfs layers
   * Resolve and run environments on the command line

environment:
  kind: PipEnv
  variables:
    SENTRY_ENVIRONMENT: development

components:

- kind: PythonPackage
  name: python
  lint:
    black: true
    python3: false
    mypy: true
  test:
    command: spfs run - pytest
  install:
    enabled: true
  deploy:
    rez.enabled: false

- kind: HugoDocs
  name: docs
  location: docs
- kind: RPMPackage
  name: rpm
  spec_file: spk.spec
