version: 0.2.1
release_notes: |
  * Fix bug where spfs objects were not automatically synced


environment:
  kind: PipEnv
  variables:
    SENTRY_ENVIRONMENT: development

components:

- kind: PythonPackage
  name: python
  lint:
    black: true
    python3: false
    mypy: true
  test:
    command: spfs run - pytest
  install:
    enabled: true
  deploy:
    rez.enabled: false

- kind: HugoDocs
  name: docs
  location: docs
- kind: RPMPackage
  name: rpm
  spec_file: spk.spec
