[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = "2018"
name = "spk"
version = "0.29.2"

[lib]
crate-type = ["cdylib"]
name = "spk"
path = "src/lib.rs"

[features]
default = ["extension-module"]
extension-module = ["pyo3/extension-module"]

[dependencies]
itertools = "0.9"
pyo3 = "0.13.2"
relative-path = "1.3.2"
spfs = {git = 'https://github.com/imageworks/spfs', tag = 'v0.28.1'}
tracing = "0.1.25"
tracing-subscriber = "0.2.16"

[dev-dependencies]
rstest = "0.9.0"
