[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = "2018"
name = "spk"
version = "0.30.0"

[lib]
crate-type = ["cdylib"]
name = "spk"
path = "src/lib.rs"

[features]
default = ["extension-module"]
extension-module = ["pyo3/extension-module"]

[dependencies]
colored = "2.0.0"
data-encoding = "2.3.0"
dyn-clone = "1.0.4"
indexmap = "1.7.0"
itertools = "0.9"
once_cell = "1.8.0"
pyo3 = {version = "0.14.1", features = ["hashbrown"]}
relative-path = "1.3.2"
ring = "0.16.15"
serde = {version = "1.0.117", features = ["derive"]}
serde_derive = "1.0.118"
serde_json = "1.0.57"
serde_yaml = "0.8.17"
spfs = {git = 'https://github.com/imageworks/spfs', tag = 'v0.28.4'}
sys-info = "0.9.0"
tempdir = "0.3.7"
tracing = "0.1.25"
tracing-subscriber = "0.2.16"
regex = "1.5.4"
url = "2.2"

[dev-dependencies]
rstest = "0.9.0"
