[profile.release]
lto = true
codegen-units = 1

[workspace]
members = [
    "crates/spfs-encoding",
    "crates/spfs",
    "crates/spk-build",
    "crates/spk-cli/*",
    "crates/spk-exec",
    "crates/spk-launcher",
    "crates/spk-schema",
    "crates/spk-solve",
    "crates/spk-solve/crates/*",
    "crates/spk-storage",
    "crates/spk",
]
