[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = "2018"
name = "spk"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]
name = "spk"
path = "src/lib.rs"

[dependencies]
pyo3 = {version = "0.13.2", features = ["extension-module"]}
spfs = {git = 'https://gitlab.spimageworks.com/spi/dev/dev-ops/spfs', branch = 'rust-conversion'}
