[profile.release]
lto = true
codegen-units = 1

[workspace]
members = [
    "crates/spfs-encoding",
    "crates/spfs",
    "crates/spk-build",
    "crates/spk-cli/*",
    "crates/spfs-cli/*",
    "crates/spk-exec",
    "crates/spk-launcher",
    "crates/spk-schema",
    "crates/spk-solve",
    "crates/spk-solve/crates/*",
    "crates/spk-storage",
    "crates/spk",
]

[workspace.dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
procfs = "0.13.2"