[package]
authors = { workspace = true }
edition = { workspace = true }
name = "spfs-cli-enter"
version = { workspace = true }

[[bin]]
name = "spfs-enter"
path = "src/cmd_enter.rs"

[features]
sentry = ["spfs-cli-common/sentry"]

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
nix = { workspace = true }
spfs = { path = "../../spfs" }
spfs-cli-common = { path = "../common" }
tokio = { version = "1.20", features = ["rt", "rt-multi-thread"] }
tracing = { workspace = true }
url = "2.2"
