[package]
authors = { workspace = true }
edition = { workspace = true }
name = "spk-cmd-render"
version = { workspace = true }

[lints]
workspace = true

[dependencies]
miette = { workspace = true, features = ["fancy"] }
async-trait = { workspace = true }
clap = { workspace = true }
dunce = { workspace = true }
spfs = { workspace = true }
spk-cli-common = { workspace = true }
spk-exec = { workspace = true }
spk-storage = { workspace = true }
tokio = { workspace = true, features = ["rt"] }
tracing = { workspace = true }
