[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = "2021"
name = "spk-cmd-repo"
version = "0.36.0"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true }
spk-cli-common = { path = '../common' }
spk-storage = { path = '../../spk-storage' }
tracing = { workspace = true }
