[package]
authors = { workspace = true }
edition = { workspace = true }
name = "spk-cmd-repo"
version = { workspace = true }
license-file = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
readme = { workspace = true }
description = { workspace = true }

[lints]
workspace = true

[dependencies]
miette = { workspace = true, features = ["fancy"] }
async-trait = { workspace = true }
clap = { workspace = true }
spk-cli-common = { workspace = true }
spk-storage = { workspace = true }
tracing = { workspace = true }
