[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = "2021"
name = "spk-cmd-make-binary"
version = "0.36.0"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true }
futures = "0.3.9"
spk-build = { path = '../../spk-build' }
spk-cli-common = { path = '../common' }
spk-schema = { path = '../../spk-schema' }
spk-storage = { path = '../../spk-storage' }
tokio = { workspace = true, features = ["rt"] }
tracing = { workspace = true }
