name: RPM Build

on:
  workflow_dispatch:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo RPM_NAME=$(rpmspec -q spfs.spec | head -n1) >> $GITHUB_ENV
      - run: echo Building ${{ env.RPM_NAME }}.rpm
      - name: build RPM package
        run: make rpm
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Binary RPM
          path: dist/rpm/RPMS/x86_64/${{ env.RPM_NAME }}.rpm
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - run: echo RPM_NAME=$(rpmspec -q spfs.spec | head -n1) >> $GITHUB_ENV
      - uses: actions/download-artifact@v2
        with:
          name: Binary RPM
      - run: docker run --privileged --net host --rm
          -v $PWD/$RPM_NAME.rpm:/tmp/$RPM_NAME.rpm
          -v $PWD/tests/integration:/tests
          centos:7
          bash -xc "yum install -y /tmp/$RPM_NAME.rpm  && bash /tests/run_tests.sh"
