name: Rust

on:
  workflow_dispatch:
  pull_request:
    branches: [master]
  push:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    container:
      image: rust
      options: --security-opt seccomp=unconfined --privileged
    steps:
      - uses: actions/checkout@v2
      - name: Prepare Container
        run: |
          apt-get update
          # nodejs is needed for rust-cache (when using `act`)
          apt-get install -y libcap2-bin sudo nodejs cmake
          rustup component add clippy rustfmt
      - uses: Swatinem/rust-cache@v1
      - name: Build Slim
        run: make debug FEATURES=
      - name: Build Default
        run: make debug
      - name: Build Server
        run: make debug FEATURES=server,cli
      # Run test before lint, lint takes a while and it is useful to know that
      # the tests are failing before knowing if the lints are passing.
      - name: Test
        run: make test FEATURES=server,cli
      - name: Lint
        run: make lint FEATURES=server,cli
      - name: Integration Test
        run: |
          make install-debug FEATURES=server,cli
          ORIGIN_REPO=/tmp/spfs-repos/origin
          mkdir -p "$ORIGIN_REPO"
          # Pre-create a repo
          SPFS_REMOTE_origin_ADDRESS="file://${ORIGIN_REPO}?create=true" spfs ls-tags -r origin
          export SPFS_REMOTE_origin_ADDRESS="file://${ORIGIN_REPO}"
          # Disable cnproc because we're in a container
          export SPFS_MONITOR_DISABLE_CNPROC=1
          # Run tests as a normal user to verify privilege escalation
          useradd -m e2e
          su e2e -c tests/integration/run_tests.sh
