name: Rust

on:
  workflow_dispatch:
  pull_request:
    branches: [master]
  push:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install -y libcap-dev
      - name: Build
        run: make debug
      - name: Lint
        run: make lint
      # For tests that need to run spfs-* binaries, install a
      # debug build into /usr/bin
      - name: Stage Binaries
        run: make install-debug
      - name: Test
        run: make test
