name: Rust

on:
  workflow_dispatch:
  pull_request:
    branches: [master]
  push:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install -y libcap-dev
      - uses: Swatinem/rust-cache@v1
      - name: Build
        run: make debug
      - name: Lint
        run: make lint
      - name: Test
        run: make test
