[package]
authors = { workspace = true }
edition = { workspace = true }
name = "spk-cli-group3"
version = { workspace = true }

[lints]
workspace = true

[dependencies]
miette = { workspace = true, features = ["fancy"] }
async-trait = { workspace = true }
clap = { workspace = true }
colored = { workspace = true }
futures = { workspace = true }
spfs = { workspace = true }
spk-cli-common = { workspace = true }
spk-storage = { workspace = true }
spk-schema = { workspace = true }
spfs-cli-common = { workspace = true }
tracing = { workspace = true }
tokio = "1.20"

[dev-dependencies]
tar = "0.4.3"
spk-build = { workspace = true }
rstest = { workspace = true }
