[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = "2021"
name = "spk-cli-group3"
version = "0.36.0"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
clap = { version = "3.2", features = ["derive", "env"] }
colored = "2.0.0"
spk-cli-common = { path = '../common' }
spk-storage = { path = '../../spk-storage' }
spk-schema = { path = '../../spk-schema' }
tracing = "0.1.35"
