[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = "2021"
name = "spk-cmd-env"
version = "0.36.0"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true }
spfs = { version = '0.34.6', path = "../../spfs" }
spk-cli-common = { path = '../common' }
spk-exec = { path = '../../spk-exec' }
tokio = { workspace = true, features = ["rt"] }
tracing = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
nix = "0.24.1"
