[package]
authors = { workspace = true }
edition = { workspace = true }
name = "spk-cmd-du"
version = { workspace = true }

[lints]
workspace = true

[dependencies]
miette = { workspace = true, features = ["fancy"] }
async-stream = "0.3"
async-trait = { workspace = true }
clap = { workspace = true }
colored = { workspace = true }
futures = "0.3.9"
itertools = { workspace = true }
spfs = { workspace = true }
spk-build = { workspace = true }
spk-cli-common = { workspace = true }
spk-solve = { workspace = true }
spk-storage = { workspace = true }
spk-schema = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true, features = ["rt"] }
