[package]
authors = ["Nichol Yip <nyip@imageworks.com>"]
edition = { workspace = true }
name = "spk-cmd-du"
version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
async-trait = "0.1"
clap = { version = "3.2", features = ["derive", "env"] }
colored = "2.0.0"
futures = "0.3.9"
itertools = "0.10"
serde_yaml = "0.8.17"
spfs = { version = '0.39.1', path = "../../spfs" }
spk-cli-common = { path = '../common' }
spk-storage = { path = '../../spk-storage' }
spk-schema = { path = '../../spk-schema' }
tracing = "0.1.35"