[package]
authors = ["Nichol Yip <nyip@imageworks.com>"]
edition = { workspace = true }
name = "spk-cmd-du"
version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true }
colored = { workspace = true }
futures = "0.3.9"
itertools = "0.10"
spfs = { version = '0.39.1', path = "../../spfs" }
spk-cli-common = { path = '../common' }
spk-storage = { path = '../../spk-storage' }
spk-schema = { path = '../../spk-schema' }
tracing = { workspace = true }