version: 0.33.1
release_notes: |
  * Sync up with github:
  * - async API
  * - client/server support

toolchain:
  - kind: Rust

components:
  - kind: RustBinary
    name: spfs
    ci_config:
      parallel: true

  - name: rpm
    kind: RPMPackage
    spec_file: .site/spi/spfs.spec
    ci_config:
      parallel: true

  - name: integration-tests
    kind: GenericBash
    test:
      - export CENTOS_IMAGE=docker-local.artifactory.spimageworks.com/gitlab/spi/dev/infrastructure/api/docker/spi-centos/centos-7.9.2009
      - docker pull $CENTOS_IMAGE
      - docker run --privileged --rm
        -v $PWD/dist/rpm/RPMS/x86_64:/tmp/rpms
        -v $PWD/tests/integration:/tests
        $CENTOS_IMAGE
        bash -xc "yum install -y /tmp/rpms/*.rpm  && bash /tests/run_tests.sh"
    ci_config:
      parallel: true
      needs:
        - component: rpm
          artifacts: true
      tags:
        - docker

  - kind: HugoDocs
    name: docs
    location: docs
    ci_config:
      parallel: true

  - kind: SentryRelease
    name: sentry
    project: spfs
    deploy.enabled: true
    ci_config:
      parallel: true
      needs:
        - component: rpm

ci_config:
  all:
    variables:
      - SPDEV_CONFIG_FILE: .site/spi/.spdev.yaml
