[package]
authors = { workspace = true }
edition = { workspace = true }
name = "spk-solve-macros"
version = { workspace = true }

[lints]
workspace = true

[features]
migration-to-components = []

[dependencies]
serde_json = { workspace = true }
spfs = { workspace = true }
spk-schema = { workspace = true }
