[package]
name = "progress_bar_derive_macro"
version = { workspace = true }
edition = { workspace = true }

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"
indicatif = { workspace = true }

[dev-dependencies]
tracing = { workspace = true }
