[package]
authors = { workspace = true }
edition = { workspace = true }
name = "spk-solve-solution"
version = { workspace = true }

[lints]
workspace = true

[features]
migration-to-components = [
    "spk-schema/migration-to-components",
    "spk-storage/migration-to-components",
]

[dependencies]
colored = { workspace = true }
console = { workspace = true }
itertools = { workspace = true }
spfs = { path = "../../../spfs" }
spk-schema = { path = "../../../spk-schema" }
spk-storage = { path = "../../../spk-storage" }
thiserror = { workspace = true }
miette = { workspace = true }
