[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = { workspace = true }
name = "spk-cmd-install"
version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true }
colored = { workspace = true }
futures = "0.3.9"
spk-cli-common = { path = '../common' }
spk-exec = { path = '../../spk-exec' }
spk-schema = { path = '../../spk-schema' }
tokio = { workspace = true, features = ["rt"] }
