[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = "2021"
name = "spk-cmd-convert"
version = "0.36.0"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true }
spk-cli-common = { path = '../common' }
spk-cmd-env = { path = "../cmd-env" }
