[package]
authors = { workspace = true }
edition = { workspace = true }
name = "spk-cmd-convert"
version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true }
spk-cli-common = { path = '../common' }
spk-cmd-env = { path = "../cmd-env" }
