[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = { workspace = true }
name = "spfs-cli-clean"
version = "0.34.6"

[[bin]]
name = "spfs-clean"
path = "src/cmd_clean.rs"

[features]
sentry = ["spfs-cli-common/sentry"]

[dependencies]
chrono = { workspace = true }
clap = { workspace = true }
colored = "2.0"
question = "0.2.2"
spfs = { path = "../../spfs" }
spfs-cli-common = { path = "../common" }
tokio = { version = "1.20", features = ["rt", "rt-multi-thread"] }
tracing = "0.1.22"
