[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = "2021"
name = "spk-exec"
version = "0.36.0"

[dependencies]
spfs = { version = '0.34.6', path = "../spfs" }
spk-schema = { path = '../spk-schema' }
spk-storage = { path = "../spk-storage" }
spk-solve = { path = "../spk-solve" }
thiserror = "1.0"
tracing = { workspace = true }
