[package]
authors = { workspace = true }
edition = { workspace = true }
name = "spk-cli-group1"
version = { workspace = true }

[lints]
workspace = true

[features]
sentry = ["spk-solve/sentry"]

[dependencies]
miette = { workspace = true, features = ["fancy"] }
async-trait = { workspace = true }
clap = { workspace = true }
clap_complete = { workspace = true }
colored = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
spfs = { workspace = true }
spk-cli-common = { workspace = true }
spk-solve = { workspace = true }
spk-schema = { workspace = true }
spk-storage = { workspace = true }
strip-ansi-escapes = { version = "0.1.1" }
tokio = { workspace = true, features = ["rt"] }
tracing = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
spk-solve-macros = { workspace = true }
spk-solve-solution = { workspace = true }
