[package]
authors = { workspace = true }
edition = { workspace = true }
name = "spk-schema-foundation"
version = { workspace = true }
license-file = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
readme = { workspace = true }
description = { workspace = true }

[lints]
workspace = true

[features]
default = ["parsedbuf-serde"]
# activates serde within the generated code from parsedbuf macros
parsedbuf-serde = []
migration-to-components = []

[dependencies]
arc-swap = { workspace = true }
async-trait = { workspace = true }
colored = { workspace = true }
data-encoding = "2.3"
enum_dispatch = "0.3.8"
format_serde_error = { version = "0.3", default-features = false, features = [
    "serde_yaml",
    "colored",
] }
ignore = "0.4.18"
itertools = { workspace = true }
nom = { workspace = true }
nom-supreme = { workspace = true }
once_cell = { workspace = true }
paste = "1.0"
parsedbuf = { workspace = true }
rand = { workspace = true }
relative-path = { workspace = true }
ring = { workspace = true }
rstest = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_yaml = { workspace = true }
spfs = { workspace = true }
strum = { workspace = true, features = ["derive"] }
sys-info = "0.9.0"
tempfile = { workspace = true }
thiserror = { workspace = true }
miette = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-capture = { workspace = true }
variantly = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
