[package]
authors = { workspace = true }
edition = { workspace = true }
name = "spk-cmd-test"
version = { workspace = true }

[lints]
workspace = true

[dependencies]
miette = { workspace = true, features = ["fancy"] }
async-trait = { workspace = true }
clap = { workspace = true }
spfs = { workspace = true }
spk-build = { workspace = true }
spk-cli-common = { workspace = true }
spk-exec = { workspace = true }
spk-solve = { workspace = true }
spk-schema = { workspace = true }
spk-storage = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["rt"] }
tracing = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
spk-cmd-build = { workspace = true }
