[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
default-run = "spfs"
edition = "2021"
name = "spfs-cli-common"
version = "0.34.6"

[[bin]]
name = "spfs"
path = "src/bin.rs"

[[bin]]
name = "spfs-clean"
path = "src/cmd_clean.rs"

[[bin]]
name = "spfs-enter"
path = "src/cmd_enter.rs"

[[bin]]
name = "spfs-join"
path = "src/cmd_join.rs"

[[bin]]
name = "spfs-render"
path = "src/cmd_render.rs"

[[bin]]
name = "spfs-monitor"
path = "src/cmd_monitor.rs"


[features]
sentry = ["dep:sentry"]

[dependencies]
async-recursion = "1.0"
async-stream = "0.3"
async-trait = "0.1.52"
caps = "0.5.3"
chrono = { version = "0.4.19", features = ["serde"] }
clap = { version = "3.2", features = ["derive", "env"] }
close-err = "1.0"
cnproc = { git = "https://github.com/rydrman/cnproc-rs", branch = "act-like-iterator" }
colored = "2.0"
config = "0.13.1"
data-encoding = "2.3"
expanduser = "1.2"
faccess = "0.2.3"
futures = "0.3.9"
gitignore = "1.0"
glob = "0.3.0"
hyper = { version = "0.14.16", features = ["client"] }
indicatif = "0.16.2"
itertools = "0.10.3"
lazy_static = "1.4"
libc = "0.2.80"
nix = "0.24.1"
once_cell = "1.8"
procfs = "0.13.2"
prost = "0.11"
question = "0.2.2"
rand = "0.8.5"
relative-path = "1.3"
ring = "0.16.15"
semver = "1.0"
sentry = { version = "0.27.0", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
serde_qs = "0.10.1"
spfs = { path = "../../spfs" }
spfs-encoding = { path = "../../spfs-encoding" }
strum_macros = "0.24.2"
tar = "0.4.30"
tempfile = "3.3"
tokio = { version = "1.20", features = [
    "fs",
    "io-util",
    "io-std",
    "rt",
    "rt-multi-thread",
    "macros",
    "sync",
    "process",
    "signal",
] }
tokio-stream = { version = "0.1", features = ["net"] }
tokio-util = { version = "0.7.3", features = ["compat"] }
tonic = "0.8"
tracing = "0.1.22"
tracing-subscriber = { version = "0.3.14", features = ["env-filter"] }
url = { version = "2.2", features = ["serde"] }
uuid = { version = "1.1", features = ["v4"] }
walkdir = "2.3"
whoami = "1.2"
thiserror = "1.0"
