[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = "2021"
name = "spfs-cli-common"
version = "0.34.6"

[features]
sentry = ["dep:sentry"]

[dependencies]
clap = { version = "3.2", features = ["derive", "env"] }
sentry = { version = "0.27.0", optional = true }
spfs = { path = "../../spfs" }
tracing = "0.1.22"
tracing-subscriber = { version = "0.3.14", features = ["env-filter"] }
