[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = { workspace = true }
name = "spfs-cli-common"
version = "0.34.6"

[features]
sentry = ["dep:sentry", "dep:whoami", "spfs/sentry", "dep:strip-ansi-escapes", "dep:serde_json", "dep:sentry-tracing"]

[dependencies]
clap = { workspace = true }
libc = { workspace = true }
sentry = { workspace = true, optional = true }
sentry-tracing = { version = "0.27.0", optional = true }
serde_json = { version = "1.0.57", optional = true}
spfs = { path = "../../spfs" }
strip-ansi-escapes = { workspace = true, optional = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
whoami = { version = "1.2", optional = true }
