[package]
authors = { workspace = true }
edition = { workspace = true }
name = "spk-schema"
version = { workspace = true }

[lints]
workspace = true

[features]
migration-to-components = ["spk-schema-foundation/migration-to-components"]

[dependencies]
data-encoding = "2.3"
dunce = { workspace = true }
enum_dispatch = "0.3.8"
format_serde_error = { version = "0.3", default_features = false, features = [
    "serde_yaml",
    "colored",
] }
ignore = "0.4.18"
indexmap = { workspace = true }
itertools = { workspace = true }
nom = { workspace = true }
regex = { workspace = true }
relative-path = "1.3"
ring = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_yaml = { workspace = true }
serde_json = { workspace = true }
spfs = { workspace = true }
shellexpand = "3.1.0"
spk-config = { workspace = true }
spk-schema-foundation = { workspace = true }
spk-schema-ident = { workspace = true }
spk-schema-liquid = { workspace = true }
strum = { workspace = true }
sys-info = "0.9.0"
tempfile = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
miette = { workspace = true }

[dev-dependencies]
proptest = "1.0.0"
rstest = { workspace = true }
