[package]
authors = { workspace = true }
edition = { workspace = true }
name = "spfs-cli-join"
version = { workspace = true }

[lints]
workspace = true

[[bin]]
name = "spfs-join"
path = "src/cmd_join.rs"

[features]
sentry = ["spfs-cli-common/sentry"]

[dependencies]
clap = { workspace = true }
futures = { workspace = true }
miette = { workspace = true, features = ["fancy"] }
spfs = { workspace = true }
spfs-cli-common = { workspace = true }
tokio = { version = "1.20", features = ["rt", "rt-multi-thread"] }
tracing = { workspace = true }
