[package]
authors = { workspace = true }
edition = { workspace = true }
name = "spk-cli-group4"
version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true }
colored = { workspace = true }
futures = { workspace = true }
serde_yaml = "0.8.17"
spfs = { path = "../../spfs" }
spk-cli-common = { path = '../common' }
spk-schema = { path = '../../spk-schema' }
tokio = { workspace = true, features = ["rt"] }
tracing = { workspace = true }
