version: 0.32.0
release_notes: |
  - convert api module to rust
  - update to latest spfs
  - update build scripts to use bash instead of sh

toolchain:
  - kind: Rust
  - kind: Pipenv
  - kind: Shell
    variables:
      SENTRY_ENVIRONMENT: development
      PATH: $SPDEV_ENV/bin:$PATH

components:
  - kind: PythonPackage
    name: python
    lint:
      black: true
      python3: false
      mypy: true
    test:
      command: spfs run - -- pytest
    install:
      enabled: true
    deploy:
      rez.enabled: false

  - kind: RustCrate
    name: spk

  - kind: HugoDocs
    name: docs
    location: docs

  - kind: RPMPackage
    name: rpm
    spec_file: spk.spec

    # bootstrap packages that need to go out with any new features
  - kind: SPKPackage
    name: spk-stdfs
    version: 1.0.0
    spec_file: packages/stdfs/stdfs.spk.yaml
  - kind: SPKPackage
    name: spk-gcc48
    version: 4.8.5
    spec_file: packages/gcc/gcc48.spk.yaml
  - kind: SPKPackage
    name: spk-gcc63
    version: 6.3.1
    spec_file: packages/gcc/gcc63.spk.yaml

  - kind: SentryRelease
    name: sentry
    project: spk
    deploy:
      enabled: true

  - kind: WordpressReleaseNotes
    name: wp-release
    email:
      sender:
        name: SPK Team
