[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = { workspace = true }
name = "spk-cmd-make-source"
version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true }
spk-build = { path = '../../spk-build' }
spk-cli-common = { path = '../common' }
spk-schema = { path = '../../spk-schema' }
spk-storage = { path = '../../spk-storage' }
tracing = { workspace = true }
