on: [push]
name: coverage
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      env:
        SPFS_PULL_USERNAME: ${{ secrets.SPFS_PULL_USERNAME }}
        SPFS_PULL_PASSWORD: ${{ secrets.SPFS_PULL_PASSWORD }}
      image: xd009642/tarpaulin
      options: --security-opt seccomp=unconfined --privileged
    steps:
      - name: Setup spfs repos
        run: |
          mkdir -p /tmp/spfs-repos/local
          mkdir -p /tmp/spfs-repos/origin
          cat >/etc/spfs.conf << EOF
          [storage]
          root = /tmp/spfs-repos/local

          [remote.origin]
          address = file:///tmp/spfs-repos/origin?create=true
          EOF
      - name: Install prerequisites
        run: |
          apt-get update
          apt-get install --yes libcap2-bin tcsh expect rsync
          # spfs "custom build command" needs rustfmt?
          rustup component add rustfmt
      - name: Checkout spfs
        uses: actions/checkout@v3
        with:
          repository: imageworks/spfs
          token: ${{ secrets.SPFS_PULL_PASSWORD }}
          path: spfs
      - name: Cache spfs installation
        id: cache-spfs-installation
        uses: actions/cache@v3
        env:
          cache-name: spfs-installation
        with:
          path: spfs/target/release
          key: cargo-toml-${{ hashFiles('spfs/Cargo.toml') }}
      - if: steps.cache-spfs-installation.cache-hit == 'true'
        name: Restore spfs build from cache
        run: |
          cd spfs
          cp target/release/spfs* /usr/bin/
          # No sudo installed; we're already root!
          sed -i "s|sudo ||" Makefile
          make setcap
      - if: steps.cache-spfs-installation.cache-hit != 'true'
        name: Build and install spfs
        run: |
          cd spfs
          # No sudo installed; we're already root!
          sed -i "s|sudo ||" Makefile
          make install
      - uses: actions/checkout@v3
        with:
          path: spk
      - uses: Swatinem/rust-cache@v1
        with:
          working-directory: spk
      - name: Generate code coverage
        run: |
          cd spk
          sed -i "s|github.com|$SPFS_PULL_USERNAME:$SPFS_PULL_PASSWORD@github.com|" Cargo.toml
          spfs run - -- cargo tarpaulin --verbose --all-features --timeout 120 --out Xml
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
