on:
  pull_request:
    paths:
      # Only run coverage report if the sources have changed
      - "src/**.rs"
      - "crates/**.rs"
  push:
    branches:
      - master
    paths:
      # Only run coverage report if the sources have changed
      - "src/**.rs"
      - "crates/**.rs"

name: Code Coverage
jobs:
  codecov:
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin
      options: --security-opt seccomp=unconfined --privileged
    steps:
      - name: Setup spfs repos
        run: |
          mkdir /spfs
          mkdir -p /tmp/spfs-repos/local
          mkdir -p /tmp/spfs-repos/origin
          cat >/etc/spfs.conf << EOF
          [storage]
          root = /tmp/spfs-repos/local

          [remote.origin]
          address = file:///tmp/spfs-repos/origin?create=true
          EOF
      - name: Install prerequisites
        run: |
          apt-get update
          apt-get install --yes libcap2-bin tcsh expect rsync sudo protobuf-compiler
          # spfs "custom build command" needs rustfmt? (protobufs?)
          rustup component add rustfmt
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v1
      - name: Generate code coverage
        run: |
          make install-debug-spfs
          spfs run - -- bash -c 'cargo tarpaulin --workspace --verbose --timeout 120 --out Xml'
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
