on: [push]
name: coverage
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      env:
        SPFS_PULL_USERNAME: ${{ secrets.SPFS_PULL_USERNAME }}
        SPFS_PULL_PASSWORD: ${{ secrets.SPFS_PULL_PASSWORD }}
      image: xd009642/tarpaulin
      options: --security-opt seccomp=unconfined
    steps:
      - uses: actions/checkout@v2
      - name: Generate code coverage
        run: |
          sed -i "s|github.com|$SPFS_PULL_USERNAME:$SPFS_PULL_PASSWORD@github.com|" Cargo.toml
          cargo tarpaulin --verbose --all-features --timeout 120 --out Xml
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
