name: Website

on: push

jobs:
  check:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
      - uses: actions/checkout@v2
      - uses: peaceiris/actions-hugo@v2
      - run: hugo
        working-directory: website
      - run: docker run -v $(pwd)./website/public:/test --rm wjdp/htmltest
