name: RPM & Packages

on:
  workflow_dispatch:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo RPM_NAME=$(rpmspec -q spk.spec | head -n1) >> $GITHUB_ENV
      - run: echo Building ${{ env.RPM_NAME }}.rpm
      - name: build RPM package
        env:
          SPFS_PULL_USERNAME: ${{ secrets.SPFS_PULL_USERNAME }}
          SPFS_PULL_PASSWORD: ${{ secrets.SPFS_PULL_PASSWORD }}
        run: make rpm
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Binary RPM
          path: dist/rpm/RPMS/x86_64/${{ env.RPM_NAME }}.rpm
  make_packages:
    runs-on: ubuntu-latest
    needs: build
    # we only build all the packages on master, or when
    # it is manually triggered by someone to run
    if: github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v2
      - name: Download Deps
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.SPFS_PULL_PASSWORD}}
          workflow: rpm.yml
          workflow_conclusion: success
          branch: master
          name: Binary RPM
          repo: imageworks/spfs
      - uses: actions/download-artifact@v2
        with:
          name: Binary RPM
      - run: mkdir -p dist/rpm/RPMS/x86_64/
      - run: cp *.rpm dist/rpm/RPMS/x86_64/
      - run: make packages.docker
