name: Rust

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      SPFS_PULL_USERNAME: ${{ secrets.SPFS_PULL_USERNAME }}
      SPFS_PULL_PASSWORD: ${{ secrets.SPFS_PULL_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - name: Check Rust Formatting
        run: cargo fmt -- --check
      - run: sudo apt-get install -y libcap-dev
      - name: Patch spfs Pull Auth
        run: sed -i "s|github.com|$SPFS_PULL_USERNAME:$SPFS_PULL_PASSWORD@github.com|" Cargo.toml
      - name: Lint Rust Code with Clippy
        run: make lint-rust
  build_and_test:
    runs-on: ubuntu-18.04
    env:
      SPFS_PULL_USERNAME: ${{ secrets.SPFS_PULL_USERNAME }}
      SPFS_PULL_PASSWORD: ${{ secrets.SPFS_PULL_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install -y libcap-dev tcsh
      - run: sudo pip3 install pipenv
      - name: Patch spfs Pull Auth
        run: sed -i "s|github.com|$SPFS_PULL_USERNAME:$SPFS_PULL_PASSWORD@github.com|" Cargo.toml
      - run: pipenv sync --dev
      - name: Build
        run: pipenv run -- cargo build --verbose
      - name: Test
        run: pipenv run -- cargo test --verbose --no-default-features
